import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'providers/trip_provider.dart';
import 'screens/trips_screen.dart';
import 'utils/app_theme.dart';

void main() async {
  // Ensure Flutter is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with platform-specific options
  // This works for Android, iOS, AND Web!
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const TripMintApp());
}

class TripMintApp extends StatelessWidget {
  const TripMintApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (context) => TripProvider(),
      child: MaterialApp(
        title: 'Trip Mint',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.darkTheme,
        home: const TripsScreen(),
      ),
    );
  }
}
